language: emacs-lisp
env:
  global:
    - GHC_VERSION=7.8.2
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
before_install:
  - bash ./install-travis.bash
  - export PATH="/opt/ghc/${GHC_VERSION}/bin:${GOPATH}/bin:${HOME}/.local/bin:${HOME}/.cabal/bin:$PATH"
install:
  # Install our packages
  - make EMACS=$EMACS deps
script:
  # Run unit tests.
  - make EMACS=$EMACS test
